# Generated by Django 5.1 on 2024-08-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(blank=True, max_length=225)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('categoty_image', models.ImageField(blank=True, upload_to='photos/cateogories')),
            ],
            options={
                'verbose_name': 'cateogory',
                'verbose_name_plural': 'categories',
            },
        ),
    ]
